run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 25
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 4
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        disabled: false
      - name: blank-imports
        disabled: false
      - name: context-as-argument
        disabled: false
      - name: error-return
        disabled: false
      - name: error-strings
        disabled: false
      - name: error-naming
        disabled: false
      - name: if-return
        disabled: false
      - name: increment-decrement
        disabled: false
      - name: var-naming
        disabled: false
      - name: var-declaration
        disabled: false
      - name: package-comments
        disabled: true
      - name: dot-imports
        disabled: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - gosec
    - revive
    - unconvert
    - whitespace
    - goconst
    - gocyclo
    - bodyclose
    - nilerr

issues:
  exclude-dirs:
    - bin
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - gosec
        - errcheck
        - gocyclo
        - dupl
